import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-10">
          <div className="flex flex-col items-center justify-center h-screen">
            <Navigation />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
